### ISSUE TITLE
Add the possibility to hard delete a primary scenario

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#262]
**Description**
The goal is to allow the deletion of a primary scenario. It is now not possible.

**Acceptance criteria**
- [x] If there is at least one other scenario in the same cycle, an exception with a good message should be raised to let the user know he/she must promote another scenario as primary before deleting the current one.
- [x] If there is no other scenario, in the same cycle, the cycle of the scenario to delete should be deleted as well.
- [x] Update old milestone to demonstrate the scenario/cycle deletion including the primary scenario deletion.
- [x] Update user man documentation and Ref man documentation.
- [ ] Update release notes for 1.2

**Comment by jrobinAV** [comment]
Pending questions to resolve :

1/ What would be the expected behavior if there are remaining scenarios on the cycle?
a/ Should we promote a random scenario as primary
b/ Should we request another scenario id that can be promoted as primary instead of the one to delete
c/ Should we allow a cycle to have no primary scenario
d/ Should we raise an exception to let the user know he/she must promote another scenario before

===> Answer: d/

2/ What would be the expected behavior if there is no other scenario on the cycle?
a/ Should we allow a cycle to have no scenario at all
b/ Should we delete the cycle as well

===> Answers: b/

**Comment by jrobinAV** [comment]
@FlorianJacta Any answer ?
