### ISSUE TITLE
DefaultCustomDocument should be documented.

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#343]
In `taipy.core.common.default_custom_document.py` the class `DefaultCustomDocument` is public and not documented (ref man).

If the class `DefaultCustomDocument` is made to be manipulated by the developer user, then it must be documented (and probably referenced in the `MongoDataNode` documentation (ref man and user man)).
Otherwise, the class DefaultCustomDocument should be renamed to `_DefaultCustomDocument` (as well as the module `default_custom_document` to `_default_custom_document.py`) in order to hide it in the ref manual.

Unrelated question: Why is `DefaultCustomDocument` in the common package while it is only used with json data nodes?

**Comment by trgiangdo** [comment]
The `DefaultCustomDocument` is actually for `MongoCollectionDataNode`.

About if `DefaultCustomDocument` is made to be manipulated by the developer user, the answer is no.
However, I think it's good to reference it somehow in the document, so that when a user defines a mongo_cfg without `custom_document`, he/she can see how the data is actually being handled.

Also, I put it in the common package because I planned to add a `custom_document` to JSONDataNode latter, but now I think it will overlap with DefaultJSONEncoder and DefaultJSONDecoder.

**Comment by jrobinAV** [comment]
After discussion, it seems that `DefaultCustomDocument` will be manipulated by the developer when he/she does a `my_mongo_datanode.read()`.
The `DefaultCustomDocument` should have a docstring documentation for the refmanual.

We also proposed to ensure to have: 
- A sentence in the user manual (in the mongo datanode config section) to explain the default document's behavior.
- more specific examples in the datanode entity page (the read section).
