### ISSUE TITLE
Check python 3.11 compatibility

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#373]

**Comment by joaoandre-avaiga** [comment]
Current Taipy Version(2.0.0) does not support python 3.11 because it depends on a version of taipy-gui that uses an older version of Gevent, which is not compatible with python 3.11. 

From what I saw, this dependency was already updated on taipy-gui, so it would be a matter of updating Taipy to use the newer version of taipy-gui. To reproduce the test that I did:

 - Install taipy: `pip install taipy`. This will fail when building the wheel for Gevent.
- Install taipy from the develop branch: `pip install git+https://github.com/Avaiga/taipy`. Since this points to the develop branch of taipy-gui, the installation proceeds without issues.

After intalling the dev version of Taipy, I ran a milestone to make sure everything works as intended, which was the case.
