### ISSUE TITLE
BUG - A scenario submission can execute multiple times the same task

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#494]
if a scenario has some overlapping pipelines, the tasks that belong to multiple pipelines are submitted once per pipeline when submitting a scenario. 

The submit method should always return a list of jobs.

**Example:** 

- Pipeline 1 config:
Task A Config -> Task B Config 

- Pipeline 2 config:
Task B Config -> Task C Config 

- Scenario config: 
Pipeline 1 Config, Pipeline 2 Config 
Task A Config -> Task B Config -> Task C Config 

**expected behavior:**

1. A user wants to submit a scenario and execute all tasks once:

```
tp.submit(scenario)
``` 
should submit task A, task B, and task C once and only once.

2. If a user wants to execute twice task B he/she can always run the following: 
```
tp.submit(scenario.pipeline1)
tp.submit(scenario.pipeline2)
```

**Comment by toan-quach** [comment]
@jrobinAV 
I think this really depends on the use case, for the example if I have datanode D as input dn of task T, task T here is used for printing out the result of datanode D. If some task T1 in pipeline P1 with task T1 makes changes to D, T can be used to print the new result, then pipeline P2 with task T2 is used to make a different change to D, should T still run to print the new value of D? Task T here can also have some conditional calculation that might give different result based on D, if task T has output datanode D_out, it might be changed based on the input D and the condition in T. In that case, I think T should be rerun as different pipelines might produce different values of D which can result in different results of T. (There's also the case of conditional Task feature that we want to have in the future to consider)
Though this does raise a question for me, if T is cachable, we run it in P1 and now it is cached, no changes are made to input dn D in pipeline P2, should T still rerun? If not, could there be a problem with it as this is the same task but in 2 different pipelines? I think the answer is No for both questions but what do you think?

**Comment by jrobinAV** [comment]
That s a specific use case where two tasks write the same output. I believe this is strange, but we can do it in Taipy.

**Comment by toan-quach** [comment]
So I think from the previous discussion, we can note down some main points:
- There are some use cases where it makes sense to have a submitted task run twice (either in the same pipeline or different pipeline)
- However, it can create some undesired side effect like where the result of several pipelines depend on which tasks finished first (because they will write to the same datanode but the input can be affect in different pipelines)
- Another strong point is that if a user desire said behavior, they should know and be awared of what they are doing. At most, we only need to log a warning for potential unwanted behavior and don't have to change what we already have.
