### ISSUE TITLE
BUG-ConfigurationUpdateBlocked should explain what it means and how to fix

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-core#588]
**Description**
ConfigurationUpdateBlocked is an error that happens often and it should explain what it means and how to fix it

**How to reproduce**

1. In notebooks:
Loading a scenario and then reloading it results in ConfigurationUpdateBlocked. To fix it: restart the kernel

![image](https://github.com/Avaiga/taipy-core/assets/62465003/e2a237e2-ccb6-463d-ac67-ed3ccbfe5db5)

2. In scripts:
I'm not sure when it happens, it seems to be when modifying the config then re-running it but I haven't found a reproducible way. To fix it: delete .data

**Runtime environment**
Please specify relevant indications.
 - Taipy version: taipy 2.2.0
 - OS: Windows

**Comment by trgiangdo** [comment]
Hi @AlexandreSajus, the ConfigurationUpdateBlocked is because after running the Core service, any update to the configuration is blocked.
This was stated in [Core service doc](https://docs.taipy.io/en/latest/manuals/running_services/#running-core), and maybe somewhere else too 😅

The simplest fix is to stop the Core service with `core.stop()`, then you can update the Configuration normally.

**Comment by trgiangdo** [comment]
However, I agree that there should be some explanation when ConfigurationUpdateBlocked happens.

Can you propose an error message that you and maybe other users would comfortable with?

**Comment by AlexandreSajus** [comment]
Hi! Yeah, sure, I'm thinking of something like:
"ConfigurationUpdateBlocked: config service should be stopped by running core.stop() before modifying it.
For more information, please refer to: https://docs.taipy.io/en/latest/manuals/running_services/#running-core."
