### ISSUE TITLE
BUG- Loading TOML Config leads to incorrect behaviors

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-core#636]
**Description**
Python and TOML configurations have different behaviors. TOML configuration has incorrect behaviors. Data Nodes are only created once, even with `Scope=Scenario`, even if multiple scenarios have been created. 

**How to reproduce**
The .data contains two scenarios as expected, but only two data nodes are present in the .data when 4 are expected (two 'a' data nodes and two 'b' data nodes).

``` python
from taipy.config import Config

import taipy as tp

def f(s):
    return s

a_cfg = Config.configure_data_node("a", default_data="a")
b_cfg = Config.configure_data_node("b")

t_cfg = Config.configure_task("t", function=f, input=a_cfg, output=b_cfg)
s_cfg = Config.configure_scenario_from_tasks("s", t_cfg)


Config.export('config.toml')


if __name__ == "__main__":
    Config.load('config.toml')

    tp.Core().run()

    print("--------------------")
    for dn_cfg in Config.data_nodes.values():
        print(dn_cfg.id + " - " + dn_cfg.scope.name, flush=True)
    print("--------------------")
    for s_cfg in Config.scenarios.values():
        for p_cfg in s_cfg.pipeline_configs:
            for task_cfg in p_cfg.task_configs:
                for dn_cfg in task_cfg.inputs:
                    if dn_cfg.scope:
                        print(dn_cfg.id + " - " + dn_cfg.scope.name, flush=True)
                    else:
                        print(dn_cfg.id + " - None", flush=True)
                for dn_cfg in task_cfg.outputs:
                    if dn_cfg.scope:
                        print(dn_cfg.id + " - " + dn_cfg.scope.name, flush=True)
                    else:
                        print(dn_cfg.id + " - None", flush=True)
    print("--------------------")
    s1 = tp.create_scenario(Config.scenarios['s'])
    s2 = tp.create_scenario(Config.scenarios['s'])
    print(len(tp.get_data_nodes()))


```

**Expected behavior**
TOML and Python configurations should have the same behavior. Data Nodes should be correctly created according to the creation of their respective scenarios.

**Runtime environment**
Please specify relevant indications.
 - Taipy version: Taipy 2.3.dev2

**Comment by jrobinAV** [comment]
## Summary of my first investigations: 
The applied config is inconsistent. I don't get the root cause, but here is the symptom. 
Instances of nested sections of an applied section do not refer to the applied instance.

**This issue has been exhibited by the fix on the clean/update. It s the same issue that has not been completely fixed.**

## Example: 
Let's call `inst_pyt_A` the instance of the data node config A of the `_python_config` : 
`inst_pyt_A = Config._python_config._sections["DATA_NODE"]["a"]`

Let's call `inst_app_A` the instance of the data node config A of the `_applied_config` : 
`inst_app_A = Config.data_nodes["a"]`

Let's call `inst_app_task_A` the instance of the data node config A of the task config T of the `_applied_config` : 
`inst_app_task_A= Config.tasks["t"].inputs["a"]`


`inst_pyt_A.scope == None`
    ==> correct
`inst_app_A.scope == SCENARIO`
    ==> correct
`inst_pyt_A is inst_app_A == False`
    ==> correct

`inst_app_task_A is inst_pyt_A == True`
    ==> **WRONG** I am expecting `inst_app_task_A is inst_app_A` to be True
`inst_app_task_A.scope == None  ` 
    ==> **WRONG**. This is the value that is used by the `create_scenario` method.

## Workaround on Core

In the `create_scenario` method on taipy-core (and all the sub-methods that create pipeline, task, and data node from config object(s)), we can retrieve the correct value by getting the section directly from `Config`, instead of getting it from the nested sections.
This does not fix the issue since the Config is still inconsistent, but that should not be a problem for taipy-core anymore.
