### ISSUE TITLE
Allow using manager directly without going through factories

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-core#679]
implement a method to build managers "the first time they are used" without going through ManagerFactory.build_manager()

The purpose is to be able to run the following code : 

```
_JobManager._get("id")
```

**Comment by joaoandre-avaiga** [comment]
A couple of points after looking into the code:
- _JobManager._get("id") <- This is already possible today, however only uses FSRepository and base Taipy Core Manager class (without enterprise).
- The _build_manager method is called for 2 reasons: Check if enterprise is installed in which case it will load both the manager class of enterprise and the _build_repository method of enterprise
```
     scenario_manager = _load_fct(
                cls._TAIPY_ENTERPRISE_CORE_MODULE + ".scenario._scenario_manager", "_ScenarioManager"
            )  # type: ignore
      build_repository = _load_fct(
                cls._TAIPY_ENTERPRISE_CORE_MODULE + ".scenario._scenario_manager_factory", "_ScenarioManagerFactory"
            )._build_repository  # type: ignore
```
- _build_manager is not required on enterprise because there's not other possible class to load in this case, the manager class on enterprise is the Top Most Class possible. The Manager Factory on enterprise today is really just a Repository Factory, because it only use is to return the correct repository class.
- We can't use the decorator to inject the manager and repository when a manager method is called because it generates a circular import. The decorator would have to call the _build_manager of the entity manager factory to check for enterprise and the decorator that would be used on the entity manager would have to also call the entity manager factory to ensure we are loading the right class. This creates a circular import(Manager imports factory and factory imports Manager.
- The only way to avoid calling _build_manager and still have the correct manager class and repository class  that I can see right now is to move the _build_repository method to another class as to avoid a circular import.

I'm gonna try to proceed on this implementation, if anyone has an issue with it let me know.
